blank_issues_enabled: false
contact_links:
  - name: StackOverflow community for OMNeT++ and Veins
    url: http://stackoverflow.com/search?q=omnet%2B%2B+veins
    about: Please ask and answer questions here.
